---
- hosts: all
  gather_facts: no
  tasks:
    - wait_for_connection:
      delay: 60
      timeout: 300

- hosts: all
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Update apt cache once before installing all the packages
      apt:
        update_cache: yes
  roles:
    - geerlingguy.github-users
    - geerlingguy.ntp
    - geerlingguy.security
    - geerlingguy.pip
    - geerlingguy.docker
    - oefenweb.hostname
